### ISSUE TITLE
No funciona el boton cerrar del modo gui

### ISSUE THREAD

**Issue by matiasdelellis** [bolichep/huayra-about#1]
Hola Pedro,
Como te dijo hector, vamos a empaquetarlo para huayra 3.1 =)

Estaba probando tu paquete, y el modo gui no cierra la ventana correctamente.. :S

Despues perfecto!!.. Gracias por todo!!! :wink:

**Comment by matiasdelellis** [comment]
p.d:

```
alumno@huayra:~/paquetes/sources/huayra-about/huayra-about$ huayra-about --gui
Traceback (most recent call last):
  File "/usr/bin/huayra-about", line 178, in <lambda>
    button_close.connect("clicked", lambda x: gtk.main_quit() )
RuntimeError: called outside of a mainloop
Traceback (most recent call last):
  File "/usr/bin/huayra-about", line 178, in <lambda>
    button_close.connect("clicked", lambda x: gtk.main_quit() )
RuntimeError: called outside of a mainloop
Traceback (most recent call last):
  File "/usr/bin/huayra-about", line 178, in <lambda>
    button_close.connect("clicked", lambda x: gtk.main_quit() )
RuntimeError: called outside of a mainloop
Traceback (most recent call last):
  File "/usr/bin/huayra-about", line 178, in <lambda>
    button_close.connect("clicked", lambda x: gtk.main_quit() )
RuntimeError: called outside of a mainloop
Traceback (most recent call last):
  File "/usr/bin/huayra-about", line 141, in <lambda>
    window.connect("destroy", lambda w: gtk.main_quit())
RuntimeError: called outside of a mainloop
/usr/bin/huayra-about:204: Warning: Source ID 47 was not found when attempting to remove it
  gtk.main()
Versión: Huayra 3 (sud) [sud,torbellino]
Base: Debian 8.0 (jessie)
Kernel lanzamiento: 3.16.0-4-amd64
Kernel versión: Debian 3.16.7-ckt9-2
```

Saludos.
